site_name: SWTomo

nav:
    - Home: 'index.md'
    - Dispersión:
        - Velocidad de fase: 'dispersion/phase.md'
        - Velocidad de group: 'dispersion/group.md'
    - Ruido ambiente:
        - Caracterísicas: 'noise/properties.md'
        - Correlaciones: 'noise/correlations.md'
    - Tomografia:
        - Mapas de dispersión: 'tomo/maps.md'
    - Ejercicios:
         - 0. Instalación: 'exercises/0_installation.md'
         - 1. Medidas de dispersión: 'exercises/1_earthquakes.md'
         - 2. Modelos de velocidad: 'exercises/2_dispersion.md'
         - 3. Correlaciones de ruido: 'exercises/3_correlations.md'
         - 4. Tomografía: 'exercises/4_tomography.md'
         - 5. Kernels de sensitividad: 'exercises/5_kernels.md'
         - 6. Inversión 1D: 'exercises/6_inversion.md'

theme: readthedocs

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
